# Generated by Django 5.1.6 on 2025-03-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('rollno', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('mobileno', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='updates')),
            ],
        ),
    ]
